"""Markdown report builder for experiment summaries."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from tools.reporting.tables import flatten_result_row, markdown_table


DEFAULT_COLUMNS = ["name", "track", "final_value", "cumulative_return", "sharpe_ratio", "max_drawdown", "turnover"]


def build_markdown_report(results: list[dict[str, Any]], *, title: str = "Experiment Report") -> str:
    rows = [flatten_result_row(result) for result in results]
    return "\n\n".join(
        [
            f"# {title}",
            markdown_table(rows, DEFAULT_COLUMNS),
            "Generated by src/tools/reporting/report_builder.py.",
        ]
    )


def write_markdown_report(path: Path, results: list[dict[str, Any]], *, title: str = "Experiment Report") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_markdown_report(results, title=title), encoding="utf-8")
    return path
