"""Markdown report builder for experiment summaries."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from tools.reporting.tables import add_baseline_deltas, flatten_result_row, markdown_table


DEFAULT_COLUMNS = [
    "name",
    "group",
    "ablation",
    "track",
    "final_value",
    "cumulative_return",
    "sharpe_ratio",
    "max_drawdown",
    "turnover",
    "delta_cumulative_return_vs_s1",
    "delta_sharpe_vs_s1",
]


def build_markdown_report(results: list[dict[str, Any]], *, title: str = "Experiment Report") -> str:
    rows = add_baseline_deltas([flatten_result_row(result) for result in results])
    return "\n\n".join(
        [
            f"# {title}",
            markdown_table(rows, DEFAULT_COLUMNS),
            "Generated by src/tools/reporting/report_builder.py.",
        ]
    )


def write_markdown_report(path: Path, results: list[dict[str, Any]], *, title: str = "Experiment Report") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_markdown_report(results, title=title), encoding="utf-8")
    return path
